MastodonC/witan.send

src/witan/send/model.clj, src/witan/send/send.clj
`total-population` and `current-year-in-loop` are both added to the `add-extra-population` function and go through the loop where they are used by the function `append-to-total-population`.
=> Put `total-popn` and `current-yr-in-loop` back in the loop

doc/intro.md, src/witan/send/send.clj, test/witan/send/send_test.clj
Calculates the number of extra individuals who will be added to the population over the course of the projection due to population growth, and returns a dataset with a row for each of these individuals for each simulation.
=> Data prep - Account for population change

src/witan/send/schemas.clj, src/witan/send/send.clj, src/witan/send/utils.clj, test/witan/send/send_test.clj, test/witan/send/utils_test.clj
=> Apply changes + test on real data

src/witan/send/send.clj, test/witan/send/send_test.clj
Last step of the loop is to join back the new population (that underwent transition changes) back to the total population.
+ Test added
+ Input data reduced in the test to bypass memory issue in circleCI
=> Join new dataset out of the loop back with the global population

src/clj/witan/send/model.clj, src/clj/witan/send/schemas.clj, src/clj/witan/send/send.clj, test/witan/send/acceptance/workspace_test.clj, test/witan/send/send_test.clj
Allow modify transitions to apply to any kind of transition (joiner, mover or leaver)
=> Refactor build-states-to-change

test/witan/send/acceptance/workspace_test.clj
This adds an optional argument for running the model so you can point it to a specific path to pull the data from. Previously this could be changed in the model code but for the validation tool it will convenient to be able to automatically roll through different input data when the model is run externally.
=> override inputs path arg for run-model

data/demo/config.edn, src/clj/witan/send/main.clj, src/clj/witan/send/send.clj, src/clj/witan/send/validate_model.clj, test/witan/send/acceptance/validate_model_test.clj
Also
- make main only deal with config parsing and selecting what to run
- make validate use the top-level config parsing (removes duplicate code)
=> **Add validation to config file**

README.md
There are a number of tools external to the model, which need to be highlighted for future use
=> Highlight available tooling in README

src/clj/witan/send/params.clj, test/witan/send/acceptance/model_test.clj, test/witan/send/acceptance/validate_model_test.clj
**Instead of copying probability distributions don't provide one.**
This is likely not a full fix.  But does a pointer to the issue that
needs solving.  We can't blindly copy distributions when we have no
data at least for joiners.
=> Instead of copying probability distributions don't provide one

project.clj
None of these upgrades required any code changes to make tests pass.
=> Upgraded to safe versions of libraries.

src/clj/witan/send/main.clj, src/clj/witan/send/metadata.clj, src/clj/witan/send/multi_config.clj, test/witan/send/acceptance/model_test.clj, test/witan/send/acceptance/validate_model_test.clj
There were too many dependencies between multi-config and other namespaces and some of the recording methods were getting out of step too. This is to avoid unnecessary repetition and tidy some things up along the way.
=> Tidy up main and multi-config

src/clj/witan/send/constants.clj, src/clj/witan/send/maths.clj, src/clj/witan/send/model/output.clj, src/clj/witan/send/model/run.clj, src/clj/witan/send/params.clj, src/clj/witan/send/schemas.clj, src/clj/witan/send/states.clj, src/clj/witan/send/step.clj, src/clj/witan/send/utils.clj, test/witan/send/send_test.clj
some+ and non-send were defined in two different places and used from all over.
=> Remove some duplicate definitions

src/clj/witan/send/params.clj
I left ay though as it describes the whole vector and is good
documentation.
=> Fixed most joker warnings in witan.send.params.

data/demo/config.edn, resources/send-charts.R, src/clj/witan/send/model/output.clj
This is https://www.pivotaltracker.com/story/show/162541051
Create a chart of the "external" ONS population data over NCYs to compare to the SEND NCYs chart.
There is an addition added to the config file, to avoid changing arguments to `output-send-results` and avoid changes to the main ns. Old configs can still be run with this code because the R will not attempt to produce the charts if it doesn't receive a full file path (which is what happens with an old config file)
=> Chart improvements

src/clj/witan/send/model/prepare.clj
Was just confirm the behaviour and parameters of using `filter-transitions-from` and `splice-ncy` and realised the filtering by year was not acting as I expected and described in scenarios.md. Now fixed, so as to filtering everything less than calendar year parameter
Expected behaviour is: "keep data where calendar year is more than input parameter year"
=> Filtering as described in scenarios.md

src/clj/witan/send/validate_model.clj, test/witan/send/acceptance/validate_model_test.clj
Output the validation results to a directory with the naming conventions "`:output-dir`-validation", so multiple validations can be run/compared/stored and not overwritten
=> Output validation to dir named for the output dir

src/clj/witan/send/check_inputs.clj, test/witan/send/check_inputs_test.clj
This extends the missing cost input check to count the number of times each missing costs occurs in the transitions input. This is useful to feedback to clients where they should focus on if they need to fix costs, and also as a warning to us if a common entity is missing a cost (and will be used as zero)
=> add count of missing costs in transitions to report

resources/send-charts.R
A couple of chart fixes. Firstly, split the settings across different charts depending on how many settings there are, rather some hard-coded value. This looked particularly stupid when there were few settings and there was 1 or 2 per chart.
Also, always start the general population chart y axis from 0 for easier comparison with the SEND charts.
=> Chart fixes

src/clj/witan/send/validate_model.clj, test/witan/send/acceptance/validate_model_test.clj
Small change to make the validation outputs play more nicely with the new client repo structure (validation was throwing an IO error toggling it on directly with their current structure).
This is a branch of a branch because I needed the testing, and wanted to avoid merge pains.. Hopefully, I've not made that harder and this can just be easily merged after #158
=> Fix validation dirs

doc/examples/modify-settings1.csv, doc/examples/modify-settings2.csv, doc/scenarios.md
I've moved the scenario examples to their own directory, to keep the input data clean.
=> move scenario examples to doc dir

doc/config.md, doc/scenarios.md, src/clj/witan/send/model/prepare.clj, src/clj/witan/send/model/run.clj
Allows one to set a specific setting to make it invalid, so everyone in that setting must leave SEND in their next transition
=> Make a setting invalid

src/clj/witan/send/model/data_products.clj, src/clj/witan/send/model/run.clj, src/clj/witan/send/utils.clj
The existing send run code was difficult to follow and debug, and the expensive reduce portion ran single threaded while the cheaper simulation bit was multi-threaded. 
This PR swaps this around. Get rid of the pmap, runs each reducing function in its own future and has explicit code for each data product produced in the reduce step.
There are some data shape dependencies based on how the old code used the reducing function composition that should be factored out in the future, but I think this is a simplification of what was there before with the advantage of being a bit faster to run as well.
witan.send.data-products replaces the roll up and calculate functions in witan.send.util `model-population-by-*` and the `reduce-rf` and `combine-rf` functions in witan.send.run. It makes it a bit …
=> More explicit and faster send run

src/clj/witan/send/check_inputs.clj, src/clj/witan/send/distributions.clj, src/clj/witan/send/model/output.clj, src/clj/witan/send/model/prepare.clj, src/clj/witan/send/model/run.clj, src/clj/witan/send/report.clj, src/clj/witan/send/send.clj, src/clj/witan/send/states.clj, src/clj/witan/send/validate_model.clj, test/witan/send/check_inputs_test.clj, test/witan/send/send_test.clj
I've used the clj-kondo linter to highlight a number of fixes. The fall into the following categories:
1. if without a second leg
2. misplaced docstrings
3. redundant lets
4. unused namespaces
5. :refer :all
Some unused vars have been left in where they are in function calls or destructuring as they serve as documentation for the structure. clj-kondo still reports these as warnings.
=> Kondo fixes

src/clj/witan/send/goal_seek.clj
I realised when aiming to decrease a transition it could be possible for the modifier to become a negative value, which is non-ideal. This fix means that the lowest modifier possible is zero.
=> goal-seek never starts lower than zero

doc/config.md, doc/scenarios.md, src/clj/witan/send/model/run.clj, src/clj/witan/send/multi_config.clj
Previously `modify-transitions-from` only allowed the ability to modify transitions at a specific future calendar year and onward. Now a user can set when they'd like to start or end modifying transitions in a projection (note: not both)
=> Allow modify transitions from or until a specific future year

doc/config.md, doc/dsdr/0002-modifying-joiner-rates.md, src/clj/witan/send/model/prepare.clj
See [DSDR](doc/0002-modifying-joiner-rates.md) for reasoning for this change
With this change I would also like to close and delete the following branches as they are now outdated by this or other work:
- [double_joiner_a](https://github.com/MastodonC/witan.send/tree/double_joiner_a)
- [remove-scenario-implementation](https://github.com/MastodonC/witan.send/tree/remove-scenario-implementation)
- [scenario-alt-2](https://github.com/MastodonC/witan.send/tree/scenario-alt-2)
=> Use original transitions when calculating joiners per year

src/clj/witan/send/model/run.clj
You can now look at the exception state here by doing
```clojure
(require 'witan.send.model.run)
(deref witan.send.model.run/exception-info)
```
and doing M-x cider-inspect-last-sexp on the deref
=> Capture the model state for inspection w/o blowing up emacs.

src/clj/witan/send/model/output.clj, src/clj/witan/send/model/run.clj
The basis of the send model is creating multiple simulations where each simulation is a count of transitions. This change outputs those simulated transitions for future analysis.
=> Output simulated transitions

src/clj/witan/send/main.clj
So we can make sure any config transformations are successful.
=> Log the config on an exception in run-recorded-send

.gitignore, deps.edn, src/clj/witan/send.clj, src/clj/witan/send/model/prepare.clj, src/clj/witan/send/model/run.clj, src/clj/witan/send/parquet.clj, src/clj/witan/send/send.clj, src/clj/witan/send/step.clj, test/witan/send/model/prepare_test.clj
The current construction of the SEND model does lots of data manipulation inside particular functions in the overall run pipeline. This makes it very difficult to figure out what is happening in each step and inspect the results, and makes it difficult to change the flow, by either directly manipulating things or by changing some of the inputs.
Furthermore, many outputs are calculated that aren't used by our current reporting system. It is also difficult to access the simulations in RAM instead we tend to re-read them from disk.
Tease apart loading the inputs, training the model, and running the model. While the first attempt may not be flexible enough, it should expose enough of the workings that we become comfortable with changing the transitions we learn from, changing the learned …
=> Deconstructed send

.circleci/config.yml, test/witan/send/model/run_test.clj
This is a mysterious change between clojure 1.9 and clojure 1.10.
I think we should make 1.10 the official minimum version. I'd like
adroddiad to rely on 1.11 for the new require :as-alias features and
things like update-vals.
I'd like to leave the commented out tests for now and re-instate some of them later.
=> Fixes a change in the way randomness is handled.

src/clj/witan/send/domain/academic_years.clj
Add defs and defns to return school-phase keywords and names given NCY, using nursery terminology for NCY -5 to -1, plus supporting defs for post-16 and post-19.
=> Add school-phase

src/clj/witan/send/domain/academic_years.clj
- Delete ncy->age and age->ncy which were using an offset of 5 (i.e. age at end of school year, or average age mid-school-year) rather than 4. For mose DfE uses age on 31-Aug prior to the start of the school year is relevant: for that use new witan.send.adriddiad.ncy/ncy->age-at-start-of-school-year.
- Delete age-group as these are defined in witan.send.adroddiad.dsg-plan.
=> Removing age defs from domain.academic-years

src/clj/witan/send/params.clj
This will throw the same error message which is helpful, when either joiner and/or population is not present
=> Throw error if joiners or population data missing
