MastodonC/witan.send

- src/witan/send/send.clj
- test/witan/send/send_test.clj
Combine the historic population with the extra population due to population growth.
> Add extra population to historic population

- src/witan/send/send.clj
- test/witan/send/send_test.clj
Group by age/placement/need and calculate average and confidence interval over simulations
> Group send projections

- src/witan/send/model.clj
- src/witan/send/send.clj
- test/witan/send/acceptance/workspace_test.clj
- test/witan/send/send_test.clj
I get the two datasets outputs when calling `post-loop-steps-1-0-0` from the repl. But I get an error trying to run the test in `workspace_test.clj`.
> SEND model outputs

- test/witan/send/acceptance/model_test.clj
**Added output file comparision check via md5s, removed bad test**
> Added output file comparision check via md5s, removed bad test

- doc/run-model-iteration.md
Details how the run-model-iteration function works
> Create run-model-iteration doc

- src/clj/witan/send/model/prepare.clj
- src/clj/witan/send/params.clj
- src/clj/witan/send/utils.clj
Moved functions to prepare and params as appropriate
> Tidy up utils some more

- src/clj/witan/send/params.clj
Take out three more functions which are not used anywhere in the repo
> rm unused fns

- src/clj/witan/send/params.clj
> Continue params clean

- src/clj/witan/send/params.clj
**introduce filtering to mover transitions in alpha-params-movers**
> WIP introduce filtering to mover transitions in alpha-params-movers

- src/clj/witan/send/model/run.clj
**Remove try except**
**Rename probs**
**start to rename distributions appropriately**
**rename symbols in sample-send-transitions**
**Keyword arguments for run functions**
**state renaming , pop func renaming**
> Remove try except

- src/clj/witan/send/step.clj
https://gist.github.com/mattford63/03031a1431b0b83146cf31598489b584#file-send-step-mechanism-org
> **Remove unnecessary external population injection into Year state**

- src/clj/witan/send/model/output.clj
- test/witan/send/acceptance/model_test.clj
- test/witan/send/acceptance/validate_model_test.clj
Addresses this long-standing but minor bug: https://www.pivotaltracker.com/story/show/157126073
> Fix csv char

- src/clj/witan/send/model/output.clj
- discover os tmp location
- add Win 10 Rscript location
> Make chart generation OS independent

- data/demo/results/SEND_Log.md
- src/clj/witan/send/report.clj
Very small change to make data quality logging readable in github markdown.
> make log readable on github

- resources/send-charts.R
- src/clj/witan/send/model/output.clj
You may need to run twice to install the optparse library.
> chart-tidy-up

- utils/R/comparative-plot-cost.R
- utils/R/comparative-plot-population.R
- utils/R/comparative-plot-settings.R
Standardised comparison plots in-line with other SEND plots. 
Temporarily commented out labelling of comparisons, with aim to fix in the future
> Standardise comparison plots

- resources/send-charts.R
Produce yearly historic sankeys for all send->send transitions, rather than just NCY6->7
> produce sankey for all AY

- README.md
- environment.yml
- src/clj/witan/send/model/output.clj
Please progress when reviewed
https://www.pivotaltracker.com/story/show/164243872
> Add a conda environment for installing R.

- resources/send-charts.R
Chart for total general population in LA over historic and projected period, requested by Brent.
> total general population chart for comparison

- src/clj/witan/send/model/output.clj
- src/clj/witan/send/model/run.clj
https://www.pivotaltracker.com/story/show/164468840
> CSV version of Transition Output

- utils/R/comparative-plot-population.R
Fixed the position of the line that delineates historic and projected population in comparative total SEND population chart
> Fix position of vline

- doc/dsdr/0001-creating-new-slices-at-the-simulation-level.md
- src/clj/witan/send/model/data_products.clj
- src/clj/witan/send/model/data_products/setting_summary.clj
- src/clj/witan/send/model/output.clj
- test/witan/send/data_products/setting_summary_test.clj
directly via the histograms rather than made up from summing things from an output file.
> Create a data product of cost per setting per year

- utils/R/comparative-charts.R
- utils/R/comparative-plot-cost.R
- utils/R/comparative-plot-population.R
- utils/R/comparative-plot-settings-needs.R
Tried to make the comparison plotting more flexible when providing paths to data.
> Allow transitions file to be elsewhere

- deps.edn
> Update to kixi.stats 0.5.5 for clj 1.11 fixes
